"""
PDF Export Service — generate styled PDF reports from AI responses.
"""
import io
from typing import Any
from xhtml2pdf import pisa  # type: ignore[import-untyped]


_CSS = """
@page {
    size: letter;
    margin: 1cm;
}
body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #333; margin: 30px; }
h1 { color: #0d6efd; font-size: 22px; border-bottom: 2px solid #0d6efd; padding-bottom: 8px; }
h2 { color: #333; font-size: 16px; margin-top: 18px; }
h3 { color: #555; font-size: 14px; }
ul, ol { margin-left: 20px; }
li { margin-bottom: 4px; }
p { line-height: 1.6; }
.header { background: #0d6efd; color: white; padding: 15px 20px; margin: -30px -30px 20px -30px; }
.header h1 { color: white; border: none; margin: 0; font-size: 20px; }
.header small { color: #cce5ff; }
.footer { text-align: center; color: #999; font-size: 10px; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }
strong { color: #0d6efd; }
code { background: #f8f9fa; padding: 2px 5px; border-radius: 3px; font-size: 11px; }
table {
    width: 100%;
    margin-bottom: 15pt;
    -pdf-keep-with-next: true;
}
th, td {
    padding: 6pt;
    border-bottom-width: 1pt;
    border-bottom-style: solid;
    border-bottom-color: #aaaaaa;
    border-top-width: 1pt;
    border-top-style: solid;
    border-top-color: #aaaaaa;
    border-left-width: 1pt;
    border-left-style: solid;
    border-left-color: #aaaaaa;
    border-right-width: 1pt;
    border-right-style: solid;
    border-right-color: #aaaaaa;
}
th {
    background-color: #f2f4f8;
    font-weight: bold;
    text-align: left;
}
"""


def generate_pdf(title: str, html_content: str, user_name: str = "User") -> bytes:  # noqa: E501
    """
    Generate a styled PDF from HTML content.
    Returns PDF as bytes.
    """
    full_html = f"""
    <html>
    <head><style>{_CSS}</style></head>
    <body>
        <div class="header">
            <h1>Virtual Career Counselor</h1>
            <small>AI-Powered Career Report for {user_name}</small>
        </div>
        <h1>{title}</h1>
        {html_content}
        <div class="footer">
            Generated by Virtual Career Counselor &mdash; Powered by Groq AI &amp; AWS<br>
            &copy; 2026 All rights reserved.
        </div>
    </body>
    </html>
    """
    buffer = io.BytesIO()
    pisa_status: Any = pisa.CreatePDF(io.StringIO(full_html), dest=buffer)  # type: ignore[no-untyped-call]
    if pisa_status.err:  # type: ignore[union-attr]
        raise RuntimeError(f"PDF generation failed with {pisa_status.err} errors")  # type: ignore[union-attr]
    return buffer.getvalue()
